### ISSUE TITLE
Tests fail (with CPAN::Changes 0.400001?)

### ISSUE THREAD

**Issue by eserte** [kentnl/Test-CPAN-Changes-ReallyStrict#2]
See subject. Fail reports will be visible in a few hours at http://matrix.cpantesters.org/?dist=Test-CPAN-Changes-ReallyStrict%201.000001

**Comment by kentfredric** [comment]
Thanks. I would have mentioned this issue in the RN, but I didn't realise this issue had been filed till after I'd released, and had mostly responded to the carpet bombing of fails I've been seeing for the last few months.

These failures *should* be fixed in `1.{'0'x5}2`.

Turns out the UTF8-ness of the data was changing, but the tools I use to compare the values is not smart enough to compare UTF8 with non-utf8, so differing utf8ness == failure.

Additionally, the underlying stuff I'm using is not smart enough to even compare utf8 with utf8 without having the difference reports being utterly confusing.

So the workaround involves:

- Making sure we at least do our initial IO to load the file the way CPAN::Changes *currently* does, to get utf8 bytes by default: https://github.com/kentnl/Test-CPAN-Changes-ReallyStrict/commit/5c2c23627bbb682e7f143b38473a2e6204ae9851 . This should eliminate most problems on current versions of CPAN::Changes
- Doing a check for utf8ness before passing it to the comparison tool, and encoding utf8 characters to bytes before handing them over where possible: https://github.com/kentnl/Test-CPAN-Changes-ReallyStrict/commit/f696b9f20368dd735e9d351ff56667311e0338f5 

Thanks for the report =)
